version: "3.2"
services:
  db:
    image: postgres
    container_name: "pg_container"
    volumes:
      - ./postgres/:/var/lib/postgresql/
    environment:
          POSTGRES_DB: "${POSTGRES_DB}"
          POSTGRES_USER: "${POSTGRES_USER}"
          POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
        - 5432:5432